
# error => hata

# print(a) # NameError

# int("12a") # ValueError

# print(10/0) #ZeroDivisionError

# print("denem"e) # SyntaxError


# error handling =>

# try:
#     x = 5
#     y = int(input("y : " ))
#     print(x/y)
# except (ZeroDivisionError,SyntaxError,ValueError):
#     print("sıfır gırılemez")

# try:
#     x = 10
#     y = 0
#     print(x/y)
# except Exception as ex:
#     print("yanlıs bilgi giriniz",ex)
# else:
#     print("hersey yolunda")
# finally:
#     print("finally blog calıstı")





